# Generated by Django 5.0.2 on 2024-04-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_subscription_subscribed_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_News',
            new_name='New_Article',
        ),
    ]
